# encoding: UTF-8

TRADING_DAYS_1YEAR = 252

STRATEGY_STATUS_WAITING_FOR_FIRST_QUOTE = u"等待报价推送"
STRATEGY_STATUS_RUNNING = u"运行中"
STRATEGY_STATUS_COMPLETE = u"完成"
STRATEGY_STATUS_CANCEL = u"已取消"
STRATEGY_STATUS_NOT_STARTED = u"未启动"
STRATEGY_STATUS_ORDER_WORKING = u"订单已提交"
STRATEGY_STATUS_ORDER_FAIL = u"下单失败"
STRATEGY_STATUS_ORDER_CANCELLED = u"订单已取消"
STRATEGY_STATUS_ALREADY_BUY_NEED_SELL = u"已经买入等待卖出"
STRATEGY_STATUS_ALREADY_SELL_NEED_BUY = u"已经卖出等待买入"

MARKET_CLOSE_TIME_US = "16:00:00"
MARKET_CLOSE_TIME_HK = "16:00:00"
MARKET_CLOSE_TIME_CN = "15:00:00"


TRADE_DIRECTION_SELL = u"卖"
TRADE_DIRECTION_BUY = u"买"
TRADE_DIRECTION_BUY_THEN_SELL = u"先买后卖"
TRADE_DIRECTION_SELL_THEN_BUY = u"先卖后买"
TRADE_DIRECTION_BUY_THEN_STOP = u"买后止损赢"

CROSS_DIRECTION_UP = u"低点上穿"
CROSS_DIRECTION_DOWN = u"高点下穿"

ORDER_PRICE_ORDERBOOK = u"摆盘买1卖1"
ORDER_PRICE_AVG_ORDERBOOK = u"买1卖1平均价"

STOP_ORDER_THRESHOLD_DIRECTION_GREATER = u"高于"
STOP_ORDER_THRESHOLD_DIRECTION_LESS = u"低于"